### ISSUE TITLE
won't run on Ubuntu 21.10

### ISSUE THREAD

**Issue by jonathan-chin** [hhannine/superpaper#101]
I've downloaded the 2.1.0 AppImage (both Ubuntu and non Ubuntu versions) and tried executing them. I got the following error:

`Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'`

I'm running a fresh install of Ubuntu 21.10. any ideas?

**Comment by comparesheriff** [comment]
I'm pretty sure Ubuntu 21.10 has wayland enabled by default as display server instead of x11 (xorg). Try logging out and selecting Ubuntu on Xorg in the login mask (can be accessed via the small cog in the bottom right. Then log back in and try again. [Step by Step](https://itsfoss.com/switch-xorg-wayland/)

**Comment by hhannine** [comment]
@jonathan-chin Is this issue still ongoing / open?

**Comment by hhannine** [comment]
I'll close this issue as Wayland related, please reopen if this does not seem to be the case. Wayland support will need to be considered separately.
