### ISSUE TITLE
Error loading example.profile in Deepin

### ISSUE THREAD

**Issue by SoulEater45** [hhannine/superpaper#33]
I just made a new install of manjaro deepin and wanted to setup different wallpapers on each monitor.
While trying to open superpaper, I always get the error message "There was an error when loading profile 'example.profile'. Exiting.".
I have tried to install it from the AUR, via pip3 and using the AppImage, but all of them give me the same error.

**Comment by hhannine** [comment]
How unfortunate; it must be some property in the example file that is incompatible with your system, but this shouldn't be an issue since the examples are intended to be loaded in flexibly..

I give you three options:
1. Help troubleshoot: run superpaper with the debugging flag `-d` in terminal to see if there's a more explicit error shown.
2. Just delete the example files in ~/.config/superpaper/profiles and you should be good to go.
3. Wait a few days since I'm on the precipice of releasing a new major release; I've made some changes to profile loading but I must say that I'm not quite certain that your issue is fixed. I'd appreciate it if they cause of your issue would be found.

**Comment by hhannine** [comment]
I released a new version, could you try that if the issue persists?

**Comment by hhannine** [comment]
Have you had the chance to test this?

**Comment by hhannine** [comment]
Since I haven't heard back from you I'm hoping you got it working and I'll close this for now. If you're experiencing issues on the current release please do make a new issue, hopefully with debugging logs.

**Comment by SoulEater45** [comment]
Sorry I haven't responded. Had to postpone my Linux Setup for later, since I had work to be done.
I tested it again on i3 and on Windows and got the same error, hence the default example file did not work out of the box. But deleting them on the new version really solved my issue.
**I had to delete all of the example profiles.**
But now it works really nice and I can start it with i3.
Would be nice if you could put in the wiki is a potential problem.
My setup is also a bit wierd, since I've got a dual monitor setup side by side and a TV above them all running of a single Nvidia card. Maybe this was the Problem.

**Comment by hhannine** [comment]
Good that you got it working! Thanks for replying.

I'm suspecting (hoping) that the issue was that you initially had bad/incompatible example file from the earlier version that was not overwritten in the update.
