### ISSUE TITLE
Feature: Implement fine control of display positions

### ISSUE THREAD

**Issue by Strykar** [hhannine/superpaper#56]
I'm using a 24" monitor in a 1080x1920 (portrait) left of my new 32" monitor a 2560x1440 (landscape), both are 16:9 aspect ratio. I couldn't get the aur package to work on Arch, and am using the AppImage.

1. For the monitor `Positions` feature, a more accurate way to micro-adjust would be nice, instead of just with the mouse? Like a text box with x and y positions or even adjusting each monitor position with the keyboard?
2. Taking a screenshot which I assume is pulling the window information from X, shows the background image completely misaligned, adding a screenshot feature to Superpaper which pulls the aligned image as created and then superimposes the rest of the desktop would be great. This appears to be affected by adjusting monitor position inside Gnome's `Display` settings.
See this screenshot for that illustrates the issue - https://i.imgur.com/NPzValb.jpg

**Comment by hhannine** [comment]
Thanks. Some comments:
1. This has been requested before and I've given it a bit of thought. There's a couple of issues that I haven't come up with a neat answer to move forward with an implementation. Aside from some technical details there's the question of what kind of interface would be accurate enough and easy enough to use to be worth implementing it. If I'd implement the numerical data entry fields, the units of the position data would probably need to be explained to the user since it's probably not quite obvious. So since this is a bit complex to do (well) and a kind of a low priority, I haven't gotten around to it.

2. The thing is that with advanced span the digital image on the desktop _must_ be  misaligned for the physical image on the displays to align correctly. If you want to spoof good screenshots you should use the simple span, where the wallpaper should be aligned in the screenshot only. Implementing a screenshot feature to superpaper doesn't make sense in my view.

**Comment by Strykar** [comment]
> 1. Aside from some technical details there's the question of what kind of interface would be accurate enough and easy enough to use to be worth implementing it.

Allow the user to micro-adjust each monitor's position with the keyboard instead of only the mouse?

> 2. If you want to spoof good screenshots you should use the simple span, where the wallpaper should be aligned in the screenshot only. Implementing a screenshot feature to superpaper doesn't make sense in my view.

Thanks for clearing that up, I'll give simple span a shot.
And thank you for this software, it's great!

**Comment by hhannine** [comment]
I'll think about it if I can make the keyboard control work, or otherwise I'll probably just do the text fields where the positions of the display edges are shown for context. I'd also like to implement snapping but I already looked into that one before and it didn't look too easy with wx, and so I thought it wouldn't be worth the investment.

**Comment by hhannine** [comment]
This is improved with the new dialog from 288742ae0cc283281a627cf15d8b4c53c27b73f3.

I've given thought to the edge snapping and to me it seems that it only improves accuracy in one way and in the other the issue is not improved. Thus for now I've decided that first I'll release the new exact entry dialog to see how people like it. To me it seems to be a pretty good improvement.

**Comment by Strykar** [comment]
> I've given thought to the edge snapping and to me it seems that it only improves accuracy in one way and in the other the issue is not improved.

@hhannine Would you elaborate on this, it's unclear?

**Comment by hhannine** [comment]
Sure. Suppose you have a setup with two displays side by side. Edge snapping in the preview improves position accuracy in the horizontal direction by forcing the display edges to snap next to each other. However, one still would need to adjust the vertical position by hand and eye with no support that would enhance accuracy. As a data entry method this is super inaccurate, and not any better than the current dragging behavior is. Furthermore, in a setup like this the vertical alignment is actually more important of the two axis, since a vertical misalignment causes obvious breakages of lines. Whereas inaccuracy in the gap size is almost no problem at all since it only affects the amount of the image that is cut out, and imperfection in that is hard to see because it is affecting something that is unseen by design.

I solved this by making the text entry dialog, shown below. It allows precise adjustment of positions pretty easily.
![image](https://user-images.githubusercontent.com/47873564/96173512-a5d55300-0f30-11eb-8d92-5901339c5147.png)
