### ISSUE TITLE
Monitor positions stay at defaults when manual display sizes are set.

### ISSUE THREAD

**Issue by D0G3L0V3R** [hhannine/superpaper#83]
1. "Override detected sizes"
2. "Input display sizes manually"
3. Set desired sizes.
4. On "Save" superpaper will move monitors on the preview screen to some positions. (Always the same for set system display configuration)
5. "Positions"
6. Allign monitors in the desired way and "Save"
7. On "Apply" superpaper doesn't acknowledge changed positions and applies the ones from step 4.

Expected behavior: Superpaper applies wallpaper according to user settings.

 - OS: Arch
 - DE: KDE on X11
 - Superpaper package & version: AUR 2.1.0-1 and AppImage 2.1.0

No errors spotted when using "superpaper -d"

**Comment by Tom-ST** [comment]
Same bug appears on Windows 10.

**Comment by hhannine** [comment]
Thanks for the report, and @Tom-ST thanks for helping narrowing it down that it isn't Linux specific. I think something is messing up the saving of the positions if manual sizes are set, but I couldn't find the issue yet.

**Comment by beningodfrey4** [comment]
Any updates on this one? For now working around this by:
1. "Override detected sizes"
2. Put in the correct sizes and hit "save"
3. The preview resets and changing positions now has no effect (the bug)
4. "Apply manual offsets" and specify x,y offsets for each monitor as how you would if you were dragging the preview (the workaround)

Thankfully bezels still apply correctly after the manual offsetting, but the preview doesn't update. Understandable as I suppose it is intended for small post-hoc adjustments. 

@hhannine, regarding the messed up saving, manually adding the correct sizes to `$XDG_CONFIG_HOME/superpaper/display_systems.dat` (instead of None) seems to have no effect.

**Comment by hhannine** [comment]
This has now been fixed (70c3fd78a3bfb58cc0a2615ade52785e9ef31f00) and will be working in the next release.
