### ISSUE TITLE
latest appimage gui fine, but doesn't change wallpapers (linux mint 20.2)

### ISSUE THREAD

**Issue by linuxgirl22** [hhannine/superpaper#91]
**describe the bug**
The gui and setup works perfectly, as well as the tray icon ... thank you very much for your work on this ... but just having a glitch about applying the 2 images for 2 monitors. Error shows as ...
load_system: archive_file not found: 
/home/painter/.config/superpaper/display_systems.dat
_that location contains general_settings and a profiles folder that contains painter.profile_

**running Superpaper in terminal with the debugging flag `-d` (summary)**
GLib-GIO-Message: 22:00:01.905: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Gtk-Message: 22:00:01.906: Failed to load module "xapp-gtk3-module"
(Superpaper-2.1.0-x86_64.AppImage:6284): GdkPixbuf-WARNING **: 22:00:01.910: Cannot open pixbuf loader module file '/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
... _gdk-pixbuf-query-loaders > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
bash: /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache: No such file or directory_

get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(2560, 1440), (1920, 1080)], OFF_ARR = [(0, 0), (2560, 0)]
Display(resolution=(2560, 1440), digital_offset=(0, 0), phys_size_mm=(597, 336), detected_phys_size_mm=(597, 336), ppi=108.91792294807368, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-A-0')
Display(resolution=(1920, 1080), digital_offset=(2560, 0), phys_size_mm=(575, 323), detected_phys_size_mm=(575, 323), ppi=84.81391304347825, 
... Canvas size: [4480, 1440]
... output includes 4 runs of covering 2 monitor specs, and each time says ...
load_system: archive_file not found: /home/painter/.config/superpaper/display_systems.dat

**is the issue wallpaper spanning?**
have turned off caja extension that allows to quickly change wallpaper via right click/set as wallpaper
have tried all desktop wallpaper styles, starting with span, but no output ... at moment, set on zoom

**to reproduce**
I setup profile and 2 wallpapers, after choosing 'separate image for every display'. Press 'Apply' but wallpaper doesn't change. 

**desktop**
linux mint mate 20.2 (focal/ubuntu 20.4)
latest Superpaper appimage 2.1.0

**additional context**
saw on a thread post saying to run which gsettings ... output is /usr/bin/gsettings
looked through threads here and saw a suggestion to run this:
GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules/ ./superpaper
or install python3-wxgtk 
... but am not great with tech things and didn't want to install something I wasn't certain was needed at this point

**Comment by hhannine** [comment]
Thanks for the thorough report.

I think you might've found the solution to the issue, which you mention in the end.
Try to run the appimage in the terminal with the command
`GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules/ ./superpaper`
where "superpaper" should be the name of the AppImage. What this command does is it sets the environment variable "GIO_EXTRA_MODULES" to the value shown after the equals sign, and this change only applies to the running instance of Superpaper that is run by the command.

If the issue was recognized correctly, running Superpaper with the above command should work. If it doesn't, come post back and  include the full debug log from the beginning up to at least once trying to apply a wallpaper maybe twice just to be sure. There's some stuff that's cut out that I would like to see if it's still not working.

**Comment by linuxgirl22** [comment]
Hi @hhannine and thank you very much for your response. Running GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules/ ./Superpaper-2.1.0-x86_64.AppImage works! Awesome to be able to use different images per monitor; thank you very much for creating this.
